# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.1

    qTest Manager API Version 8.6 - 9.1

    OpenAPI spec version: 8.6 - 9.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages

requirements = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name='rpc-qtest-swagger-client',
    version='9.1.6',
    author='rpc-automation',
    author_email='rpc-automation@rackspace.com',
    license="Apache Software License 2.0",
    url='https://github.com/rcbops/qtest-swagger-client',
    keywords='swagger qtest',
    description='qTest Manager API Version 8.6 - 9.1',
    long_description='qTest Manager API Version 8.6 - 9.1',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    install_requires=requirements,
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False
)
